[advisories]
unmaintained = "workspace"

[[advisories.ignore]]
id = "RUSTSEC-2026-0009"
reason = "time is only used in examples, and we can't upgrade due to our MSRV"

[licenses]
private.ignore = true
unused-allowed-license = "allow"
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
]
