[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
cargo-binstall = "latest"

[tools."cargo:cargo-nextest"]
version = "latest"
dependencies = ["cargo-binstall"]

[tasks.test]
run = "cargo nextest run"
