name: ci
on:
  push:
    branches: [master, "1.x", "2.x"]
  pull_request:

jobs:
  test-rustls:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - os: macos-latest
            target: aarch64-apple-darwin
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - os: windows-latest
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - os: windows-latest
            features: cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors,http2,json,native-tls,spnego,text-decoding
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Cache Cargo dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Check Clippy lints
        run: cargo clippy --no-default-features --features ${{ matrix.features }}

      - name: Run tests
        run: cargo test --no-default-features --features ${{ matrix.features }}

      - name: Run example program
        run: cargo run --release --example simple --no-default-features --features ${{ matrix.features }}

  test-linux-rustls-musl-static:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v6

      - name: Install musl toolchain
        run: |
          sudo apt install -y musl-tools
          rustup target add x86_64-unknown-linux-musl

      - name: Cache Cargo dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Run tests
        run: cargo test --target x86_64-unknown-linux-musl --features ${{ env.FEATURES }}

  docs-rs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
      RUSTUP_TOOLCHAIN: nightly
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs
