name: ci
on:
  push:
    branches: [master, "1.x", "2.x"]
  pull_request:

env:
  FEATURES: cookies,psl,tls-insecure,trust-webpki-roots

jobs:
  test-rustls:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v6

      - name: Update Cargo.lock
        run: cargo update

      - name: Cache Cargo dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Check Clippy lints
        run: cargo clippy --features ${{ env.FEATURES }},unstable-interceptors

      - name: Run tests
        run: cargo test --features ${{ env.FEATURES }},unstable-interceptors

      - name: Run example program
        run: cargo run --release --example simple

  test-linux-rustls-musl-static:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v6

      - name: Install musl toolchain
        run: |
          apt install -y musl-tools
          rustup target add x86_64-unknown-linux-musl

      - name: Update Cargo.lock
        run: cargo update

      - name: Cache Cargo dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Run tests
        run: cargo test --target x86_64-unknown-linux-musl --features ${{ env.FEATURES }}

  test-windows-native-tls:
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v6

      - name: Update Cargo.lock
        run: cargo update

      - name: Cache Cargo dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Run tests
        run: cargo test --no-default-features --features ${{ env.FEATURES }},http2,json,native-tls,spnego,text-decoding

  docs-rs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
      RUSTUP_TOOLCHAIN: nightly
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs
