name: ci
on:
  push:
    branches: [master, "1.x", "2.x"]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo clippy -- -Dwarnings

  test:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            features: default,cookies,psl,spnego,tls-insecure,trust-webpki-roots,unstable-interceptors
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - runner: macos-latest
            target: aarch64-apple-darwin
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            features: cookies,psl,tls-insecure,unstable-interceptors,http2,json,native-tls,spnego,text-decoding
          - runner: windows-11-arm
            target: aarch64-pc-windows-msvc
            features: default,cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v6

      - name: Install musl toolchain
        run: sudo apt install -y musl-tools
        if: matrix.target == 'x86_64-unknown-linux-musl'

      - name: Install SPNEGO dependencies
        run: sudo apt install -y libkrb5-dev
        if: contains(matrix.runner, 'ubuntu') && contains(matrix.features, 'spnego')

      - name: Install target toolchain
        run: rustup target add ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.target }}-

      - name: Check Clippy lints
        run: cargo clippy --no-default-features --features ${{ matrix.features }}

      - name: Run tests
        run: cargo test --no-default-features --features ${{ matrix.features }}

      - name: Run example program
        run: cargo run --release --example simple --no-default-features --features ${{ matrix.features }}

  docs-rs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
      RUSTUP_TOOLCHAIN: nightly
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs
