name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v6

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --features cookies,psl,tls-insecure,trust-webpki-roots,unstable-interceptors --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
